toggle_scanning = "s"

[paired_device]
unpair = "a"
toggle_connect = "e"
toggle_trust = "t"
rename = "r"

[adapter]
toggle_pairing = "i"
toggle_power = "o"
toggle_discovery = "d"

[new_device]
pair = "a"
