[alias]
c = 'clippy'
f = 'fmt'
q = 'run -q'
qr = 'run -q --release'
rr = 'run --release'
br = 'build --release'
a = 'add'
maybe = 'add --dry-run'
do = 'doc --open'
dd = 'doc --no-deps'
ddo = 'doc --no-deps --open'
s = 'search'
seek = 'seek --fps 100'

[env]
RUST_LOG = 'trace'

[build]
jobs = -1
