[alias]
c = 'clippy'
f = 'fmt'
q = 'run -q'
qr = 'run -q --release'
rr = 'run --release'
br = 'build --release'
a = 'add'
maybe = 'add --dry-run'
do = 'doc --open'
w = 'watch -q -c -x clippy'
s = 'search'

[env]
RUST_LOG = 'trace'
