[alias]
a = 'add'
br = 'build --release'
c = 'clippy'
d = 'doc'
do = 'doc --open --no-deps'
f = 'fmt'
i = 'info'
q = 'run -q'
qr = 'run -q --release'
rr = 'run --release'
s = 'search'
seek = 'seek --fps 100'

[env]
RUST_LOG = 'trace'

[build]
jobs = -1
