# array_width = 60
# attr_fn_like_width = 70
# chain_width = 60
# fn_call_width = 60
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 82
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
# single_line_if_else_max_width = 50
# single_line_let_else_max_width = 50
# struct_lit_width = 18
# struct_variant_width = 35
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

unstable_features = true
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 110
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = false
enum_discrim_align_threshold = 20
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = false
hex_literal_case = "Upper"
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
imports_granularity = "Item"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
where_single_line = false
wrap_comments = true