[general]
# [[sort on]]
actions-on-enter = [ "save-to-clipboard", "save-to-file", "exit" ]
annotation-size-factor = 1
copy-command = "wl-copy"
corner-roundness = 0
default-fill-shapes = false
default-hide-toolbars = true
disable-notifications = true
early-exit = true
fullscreen = true
initial-tool = "arrow"
output-filename = "/home/axlefublr/iwm/sco/%Y.%m.%d-%H:%M:%S-edited.png"
primary-highlighter = "freehand"
save-after-copy = true
# [[sort off]]

[font]
family = "Inter"
style = "Regular"

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "l"
arrow = "i"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "h"

[color-palette]
palette = [
  "#ffafd7", # pink
  "#ffd75f", # yellow
  "#00d7ff", # cyan
  "#ffffff",
  "#000000",
  "#87ff5f", # salad
  "#ff2930", # red
  "#af87ff", # purple
]
