[mgr]
# [[sort on]]
count_copied = { bg = '#e491b2', fg = '#1f1e1e', bold = true }
count_cut = { bg = '#ea6962', fg = '#1f1e1e', bold = true }
count_selected = { bg = '#d3ad5c', fg = '#1f1e1e', bold = true }
cwd = { fg = '#ffafd7', bold = true }
find_keyword = { fg = '#ea6962', bold = true }
find_position = { fg = '#ea6962', bold = true }
hovered = { fg = '#e49641', bg = '#5f472d', bold = true }
marker_copied = { bg = '#e491b2', fg = '#e491b2' }
marker_cut = { bg = '#ea6962', fg = '#ea6962' }
marker_marked = { bg = '#e49641', fg = '#e49641' }
marker_selected = { bg = '#d3ad5c', fg = '#d3ad5c' }
# [[sort off]]

[tabs]
# [[sort on]]
active = { fg = 'white', bold = true }
inactive = { fg = '#928374' }
# [[sort off]]

[mode]
# [[sort on]]
normal_alt = { fg = 'white', bg = 'reset' }
normal_main = { fg = 'white', bg = 'reset' }
select_alt = { fg = 'white', bg = 'reset' }
select_main = { fg = '#1f1e1e', bg = '#e49641', bold = true }
unset_alt = { fg = 'white', bg = 'reset' }
unset_main = { fg = '#1f1e1e', bg = '#ea6962', bold = true }
# [[sort off]]

[status]
# [[sort on]]
perm_sep = { fg = '#928374' }
progress_error = { fg = '#ea6962' }
progress_label = { fg = '#1f1e1e', bold = true }
progress_normal = { fg = '#a9b665' }
sep_left = { open = '', close = '' }
sep_right = { open = '', close = '' }
# [[sort off]]

[which]
cols = 2
mask = { bg = '#212121' }
separator_style = { fg = 'white' }
cand = { fg = '#e49641' }
desc = { fg = '#d3ad5c' }

[confirm]
border = { fg = '#e49641', bold = true }
title = { fg = '#e49641' }
btn_yes = {}
btn_labels = [ 'Yes', 'No' ]

[spot]
border = { fg = '#e49641', bold = true }
title = { fg = '#e49641' }
tbl_col = { fg = '#b58cc6' }
tbl_cell = { fg = '#e49641', bg = '#5f472d', bold = true }

[notify]
title_info = { fg = '#7daea3' }
title_warn = { fg = '#e49641' }
title_error = { fg = 'red' }

[pick]
border = { fg = '#e49641', bold = true }
active = { fg = '#e49641', bg = '#5f472d', bold = true }
inactive = { fg = '#b58cc6' }

[input]
border = { fg = '#e49641', bold = true }
title = { fg = '#e49641', bold = true }

[tasks]
border = { fg = '#e49641', bold = true }
title = { fg = '#e49641', bold = true }
hovered = { fg = '#e49641', bg = '#5f472d', bold = true }

[help]
on = { fg = '#e49641' }
run = { fg = '#d3ad5c' }
hovered = { bg = '#5f472d' }
footer = { fg = 'white' }

[filetype]
rules = [
  { mime = 'inode/x-empty', fg = 'red' },      # empty file
  { name = '*', is = 'orphan', fg = 'red' },   # orphan symbolic links
  { name = '*', is = 'link', fg = '#78bf84' }, # symbolic links
  { name = '*', is = 'exec', fg = 'green' },   # executables
  # { name = '*', fg = 'white' },
  { name = '*/', fg = '#b58cc6' },
]
